import os

tables = {
    "isFileHere": ["D", "E", "F", "G", "H", "I", "J", "K", "C"],
    "ui_texts": {
        "YourScore": {"English": "Your Score", "فارسی": "امتیاز شما", "کوردی": "خاڵی تۆ"},
        "LearningPaths": {"English": "Learning Paths", "فارسی": "مسیر های آموزشی", "کوردی": "ڕێڕەوەکانی فێربوون"},
        "LessonDesc": {"English": "Lesson Description", "فارسی": "شرح درس", "کوردی": "شرۆڤەی وانە"},
        "Output": {"English": "Output", "فارسی": "خروجی", "کوردی": "دەرەنجام"},
        "Cleared": {"English": "Cleared", "فارسی": "پاک شد", "کوردی": "سڕدرایەوە"},
        "AlreadyCompleted": {"English": "Well done, but already completed", "فارسی": "آفرین ولی چالش قبلا انجام شده", "کوردی": "ئافەرین، بەڵام پێشتر کراوە"},
        "Passed": {"English": "Challenge passed successfully", "فارسی": "چالش با موفقیت پاس شد", "کوردی": "ئاڵنگارییەکە بە سەرکەوتوویی تێپەڕی"},
        "Cheat": {"English": "Cheat! Use correct commands.", "فارسی": "تقلب! از دستورات و عملگرهای درست استفاده کن.", "کوردی": "فێڵ! فەرمانە دروستەکان بەکاربهێنە."},
        "WrongOutput": {"English": "Output is incorrect.", "فارسی": "خروجی اشتباه است.", "کوردی": "دەرەنجام هەڵەیە."},
        "HelpTitle": {"English": "Challenge Hint", "فارسی": "راهنمایی چالش", "کوردی": "ڕێنمایی ئاڵنگارییە"},
        "Reverted": {"English": "Code reverted successfully", "فارسی": "کد با موفقیت برگشت", "کوردی": "کۆد بە سەرکەوتوویی گەڕایەوە"},
        "SelectLesson": {"English": "First select a lesson", "فارسی": "ابتدا یک درس را انتخاب کنید", "کوردی": "سەرەتا وانەیەک هەڵبژێرە"},
        "Error": {"English": "error", "فارسی": "error", "کوردی": "error"},
        "AboutTitle": {"English": "About Developer", "فارسی": "درباره سازنده", "کوردی": "دەربارەی گەشەپێدەر"},
        "AboutText": {
            "English": "MarCode \nAn interactive Python learning sandbox.\n\n Designed & Developed by: Ramyar Hasanpour\n\n GitHub Repository:\nhttps://github.com/RamyarHasanpour/marcode",
            "فارسی": "مارکد (MarCode)\nمحیط تعاملی و جذاب برای یادگیری پایتون.\n\n طراحی و توسعه‌یافته توسط: رامیار حسن‌پور\n\n مخزن گیت‌هاب پروژه:\nhttps://github.com/RamyarHasanpour/marcode",
            "کوردی": "مارکۆد (MarCode)\nژینگەیەکی کارلێککارانە بۆ فێربوونی پایتۆن.\n\n دیزاین و گەشەپێدان لەلایەن: ڕامیار حەسەن‌پوور\n\nکۆگای گیت‌هابی پڕۆژەکە:\nhttps://github.com/RamyarHasanpour/marcode"
        }
    },
    "ConfigUi": {
        "ColorBTNZirEdtcode": {
            "0": "#3a6ff0",
            "1": "#e8b93c",
            "2": "#5a5f6e",
            "3": "#2fb350",
            "4": "#e74c3c",
        },
        "HoverColorBTNZirEdtcode": {
            "0": "#2b5cd9",
            "1": "#d4a42b",
            "2": "#474b58",
            "3": "#269944",
            "4": "#c0392b", 
        },
        "TextBTNZirEdtcode": {
            "English": {
                "0": "Clear",
                "1": "Run",
                "2": "Check",
                "3": "Help",
                "4": "Ctrl+z",
            },
            "فارسی": {
                "0": "پاک کردن",
                "1": "اجرا",
                "2": "برسی چالش",
                "3": "راهنما",
                "4": "Ctrl+z",
            },
            "کوردی": {
                "0": "سڕینەوە",
                "1": "جێبەجێکردن",
                "2": "پشکنین",
                "3": "ڕێنمایی",
                "4": "Ctrl+z",
            }
        },
        "PyKeywordsColor": {
            "return": "#c586c0",
            "if": "#c586c0",
            "elif": "#c586c0",
            "else": "#c586c0",
            "for": "#c586c0",
            "while": "#c586c0",
            "import": "#c586c0",
            "from": "#c586c0",
            "as": "#c586c0",
            "try": "#c586c0",
            "except": "#c586c0",
            "finally": "#c586c0",
            "with": "#c586c0",
            "pass": "#c586c0",
            "break": "#c586c0",
            "continue": "#c586c0",
            "yield": "#c586c0",
            "raise": "#c586c0",
            "assert": "#c586c0",
            "del": "#c586c0",
            "async": "#c586c0",
            "await": "#c586c0",
            "match": "#c586c0",
            "case": "#c586c0",
            "def": "#569cd6",
            "class": "#569cd6",
            "lambda": "#569cd6",
            "global": "#569cd6",
            "nonlocal": "#569cd6",
            "True": "#569cd6",
            "False": "#569cd6",
            "None": "#569cd6",
            "and": "#569cd6",
            "or": "#569cd6",
            "not": "#569cd6",
            "is": "#569cd6",
            "in": "#569cd6",
            "self": "#569cd6",
            "cls": "#569cd6",
            "NotImplemented": "#569cd6",
            "Ellipsis": "#569cd6",
            "__debug__": "#569cd6",
            "int": "#4ec9b0",
            "float": "#4ec9b0",
            "complex": "#4ec9b0",
            "bool": "#4ec9b0",
            "str": "#4ec9b0",
            "bytes": "#4ec9b0",
            "bytearray": "#4ec9b0",
            "memoryview": "#4ec9b0",
            "list": "#4ec9b0",
            "tuple": "#4ec9b0",
            "range": "#4ec9b0",
            "dict": "#4ec9b0",
            "set": "#4ec9b0",
            "frozenset": "#4ec9b0",
            "object": "#4ec9b0",
            "type": "#4ec9b0",
            "slice": "#4ec9b0",
            "super": "#4ec9b0",
            "property": "#4ec9b0",
            "staticmethod": "#4ec9b0",
            "classmethod": "#4ec9b0",
            "enumerate": "#4ec9b0",
            "filter": "#4ec9b0",
            "map": "#4ec9b0",
            "reversed": "#4ec9b0",
            "zip": "#4ec9b0",
            "BaseException": "#4ec9b0",
            "BaseExceptionGroup": "#4ec9b0",
            "Exception": "#4ec9b0",
            "ExceptionGroup": "#4ec9b0",
            "ArithmeticError": "#4ec9b0",
            "AssertionError": "#4ec9b0",
            "AttributeError": "#4ec9b0",
            "BlockingIOError": "#4ec9b0",
            "BrokenPipeError": "#4ec9b0",
            "BufferError": "#4ec9b0",
            "BytesWarning": "#4ec9b0",
            "ChildProcessError": "#4ec9b0",
            "ConnectionAbortedError": "#4ec9b0",
            "ConnectionError": "#4ec9b0",
            "ConnectionRefusedError": "#4ec9b0",
            "ConnectionResetError": "#4ec9b0",
            "DeprecationWarning": "#4ec9b0",
            "EOFError": "#4ec9b0",
            "EncodingWarning": "#4ec9b0",
            "EnvironmentError": "#4ec9b0",
            "FileExistsError": "#4ec9b0",
            "FileNotFoundError": "#4ec9b0",
            "FloatingPointError": "#4ec9b0",
            "FutureWarning": "#4ec9b0",
            "GeneratorExit": "#4ec9b0",
            "IOError": "#4ec9b0",
            "ImportError": "#4ec9b0",
            "ImportWarning": "#4ec9b0",
            "IndentationError": "#4ec9b0",
            "IndexError": "#4ec9b0",
            "InterruptedError": "#4ec9b0",
            "IsADirectoryError": "#4ec9b0",
            "KeyError": "#4ec9b0",
            "KeyboardInterrupt": "#4ec9b0",
            "LookupError": "#4ec9b0",
            "MemoryError": "#4ec9b0",
            "ModuleNotFoundError": "#4ec9b0",
            "NameError": "#4ec9b0",
            "NotADirectoryError": "#4ec9b0",
            "NotImplementedError": "#4ec9b0",
            "OSError": "#4ec9b0",
            "OverflowError": "#4ec9b0",
            "PendingDeprecationWarning": "#4ec9b0",
            "PermissionError": "#4ec9b0",
            "ProcessLookupError": "#4ec9b0",
            "RecursionError": "#4ec9b0",
            "ReferenceError": "#4ec9b0",
            "ResourceWarning": "#4ec9b0",
            "RuntimeError": "#4ec9b0",
            "RuntimeWarning": "#4ec9b0",
            "StopAsyncIteration": "#4ec9b0",
            "StopIteration": "#4ec9b0",
            "SyntaxError": "#4ec9b0",
            "SyntaxWarning": "#4ec9b0",
            "SystemError": "#4ec9b0",
            "SystemExit": "#4ec9b0",
            "TabError": "#4ec9b0",
            "TimeoutError": "#4ec9b0",
            "TypeError": "#4ec9b0",
            "UnboundLocalError": "#4ec9b0",
            "UnicodeDecodeError": "#4ec9b0",
            "UnicodeEncodeError": "#4ec9b0",
            "UnicodeError": "#4ec9b0",
            "UnicodeTranslateError": "#4ec9b0",
            "UnicodeWarning": "#4ec9b0",
            "UserWarning": "#4ec9b0",
            "ValueError": "#4ec9b0",
            "Warning": "#4ec9b0",
            "ZeroDivisionError": "#4ec9b0",
            "abs": "#dcdcaa",
            "aiter": "#dcdcaa",
            "anext": "#dcdcaa",
            "all": "#dcdcaa",
            "any": "#dcdcaa",
            "ascii": "#dcdcaa",
            "bin": "#dcdcaa",
            "breakpoint": "#dcdcaa",
            "callable": "#dcdcaa",
            "chr": "#dcdcaa",
            "compile": "#dcdcaa",
            "delattr": "#dcdcaa",
            "dir": "#dcdcaa",
            "divmod": "#dcdcaa",
            "eval": "#dcdcaa",
            "exec": "#dcdcaa",
            "format": "#dcdcaa",
            "getattr": "#dcdcaa",
            "globals": "#dcdcaa",
            "hasattr": "#dcdcaa",
            "hash": "#dcdcaa",
            "help": "#dcdcaa",
            "hex": "#dcdcaa",
            "id": "#dcdcaa",
            "input": "#dcdcaa",
            "isinstance": "#dcdcaa",
            "issubclass": "#dcdcaa",
            "iter": "#dcdcaa",
            "len": "#dcdcaa",
            "locals": "#dcdcaa",
            "max": "#dcdcaa",
            "min": "#dcdcaa",
            "next": "#dcdcaa",
            "oct": "#dcdcaa",
            "open": "#dcdcaa",
            "ord": "#dcdcaa",
            "pow": "#dcdcaa",
            "print": "#dcdcaa",
            "repr": "#dcdcaa",
            "round": "#dcdcaa",
            "setattr": "#dcdcaa",
            "sorted": "#dcdcaa",
            "sum": "#dcdcaa",
            "vars": "#dcdcaa",
            "__import__": "#dcdcaa",
            "__init__": "#dcdcaa",
            "__new__": "#dcdcaa",
            "__del__": "#dcdcaa",
            "__repr__": "#dcdcaa",
            "__str__": "#dcdcaa",
            "__bytes__": "#dcdcaa",
            "__format__": "#dcdcaa",
            "__lt__": "#dcdcaa",
            "__le__": "#dcdcaa",
            "__eq__": "#dcdcaa",
            "__ne__": "#dcdcaa",
            "__gt__": "#dcdcaa",
            "__ge__": "#dcdcaa",
            "__hash__": "#dcdcaa",
            "__bool__": "#dcdcaa",
            "__getattr__": "#dcdcaa",
            "__getattribute__": "#dcdcaa",
            "__setattr__": "#dcdcaa",
            "__delattr__": "#dcdcaa",
            "__dir__": "#dcdcaa",
            "__get__": "#dcdcaa",
            "__set__": "#dcdcaa",
            "__delete__": "#dcdcaa",
            "__set_name__": "#dcdcaa",
            "__init_subclass__": "#dcdcaa",
            "__class_getitem__": "#dcdcaa",
            "__instancecheck__": "#dcdcaa",
            "__subclasscheck__": "#dcdcaa",
            "__subclasshook__": "#dcdcaa",
            "__call__": "#dcdcaa",
            "__len__": "#dcdcaa",
            "__length_hint__": "#dcdcaa",
            "__getitem__": "#dcdcaa",
            "__setitem__": "#dcdcaa",
            "__delitem__": "#dcdcaa",
            "__missing__": "#dcdcaa",
            "__iter__": "#dcdcaa",
            "__next__": "#dcdcaa",
            "__reversed__": "#dcdcaa",
            "__contains__": "#dcdcaa",
            "__add__": "#dcdcaa",
            "__sub__": "#dcdcaa",
            "__mul__": "#dcdcaa",
            "__matmul__": "#dcdcaa",
            "__truediv__": "#dcdcaa",
            "__floordiv__": "#dcdcaa",
            "__mod__": "#dcdcaa",
            "__divmod__": "#dcdcaa",
            "__pow__": "#dcdcaa",
            "__lshift__": "#dcdcaa",
            "__rshift__": "#dcdcaa",
            "__and__": "#dcdcaa",
            "__xor__": "#dcdcaa",
            "__or__": "#dcdcaa",
            "__radd__": "#dcdcaa",
            "__rsub__": "#dcdcaa",
            "__rmul__": "#dcdcaa",
            "__rmatmul__": "#dcdcaa",
            "__rtruediv__": "#dcdcaa",
            "__rfloordiv__": "#dcdcaa",
            "__rmod__": "#dcdcaa",
            "__rdivmod__": "#dcdcaa",
            "__rpow__": "#dcdcaa",
            "__rlshift__": "#dcdcaa",
            "__rrshift__": "#dcdcaa",
            "__rand__": "#dcdcaa",
            "__rxor__": "#dcdcaa",
            "__ror__": "#dcdcaa",
            "__iadd__": "#dcdcaa",
            "__isub__": "#dcdcaa",
            "__imul__": "#dcdcaa",
            "__imatmul__": "#dcdcaa",
            "__itruediv__": "#dcdcaa",
            "__ifloordiv__": "#dcdcaa",
            "__imod__": "#dcdcaa",
            "__ipow__": "#dcdcaa",
            "__ilshift__": "#dcdcaa",
            "__irshift__": "#dcdcaa",
            "__iand__": "#dcdcaa",
            "__ixor__": "#dcdcaa",
            "__ior__": "#dcdcaa",
            "__neg__": "#dcdcaa",
            "__pos__": "#dcdcaa",
            "__abs__": "#dcdcaa",
            "__invert__": "#dcdcaa",
            "__complex__": "#dcdcaa",
            "__int__": "#dcdcaa",
            "__float__": "#dcdcaa",
            "__index__": "#dcdcaa",
            "__round__": "#dcdcaa",
            "__trunc__": "#dcdcaa",
            "__floor__": "#dcdcaa",
            "__ceil__": "#dcdcaa",
            "__enter__": "#dcdcaa",
            "__exit__": "#dcdcaa",
            "__await__": "#dcdcaa",
            "__aiter__": "#dcdcaa",
            "__anext__": "#dcdcaa",
            "__aenter__": "#dcdcaa",
            "__aexit__": "#dcdcaa",
            "__copy__": "#dcdcaa",
            "__deepcopy__": "#dcdcaa",
            "__getstate__": "#dcdcaa",
            "__setstate__": "#dcdcaa",
            "__reduce__": "#dcdcaa",
            "__reduce_ex__": "#dcdcaa",
            "__sizeof__": "#dcdcaa",
            "__fspath__": "#dcdcaa",
            "__post_init__": "#dcdcaa",
            "__name__": "#9cdcfe",
            "__main__": "#9cdcfe",
            "__file__": "#9cdcfe",
            "__doc__": "#9cdcfe",
            "__dict__": "#9cdcfe",
            "__class__": "#9cdcfe",
            "__module__": "#9cdcfe",
            "__bases__": "#9cdcfe",
            "__mro__": "#9cdcfe",
            "__slots__": "#9cdcfe",
            "__annotations__": "#9cdcfe",
            "__qualname__": "#9cdcfe",
            "__package__": "#9cdcfe",
            "__spec__": "#9cdcfe",
            "__loader__": "#9cdcfe",
            "__path__": "#9cdcfe",
            "__all__": "#9cdcfe",
            "__version__": "#9cdcfe",
            "__author__": "#9cdcfe",
            "__defaults__": "#9cdcfe",
            "__kwdefaults__": "#9cdcfe",
            "__globals__": "#9cdcfe",
            "__closure__": "#9cdcfe",
            "__code__": "#9cdcfe",
            "__func__": "#9cdcfe",
            "__self__": "#9cdcfe",
            "__wrapped__": "#9cdcfe",
            "__weakref__": "#9cdcfe",
            "__match_args__": "#9cdcfe",
            "__dataclass_fields__": "#9cdcfe",
            "capitalize": "#dcdcaa",
            "casefold": "#dcdcaa",
            "center": "#dcdcaa",
            "count": "#dcdcaa",
            "encode": "#dcdcaa",
            "endswith": "#dcdcaa",
            "expandtabs": "#dcdcaa",
            "find": "#dcdcaa",
            "format_map": "#dcdcaa",
            "index": "#dcdcaa",
            "isalnum": "#dcdcaa",
            "isalpha": "#dcdcaa",
            "isascii": "#dcdcaa",
            "isdecimal": "#dcdcaa",
            "isdigit": "#dcdcaa",
            "isidentifier": "#dcdcaa",
            "islower": "#dcdcaa",
            "isnumeric": "#dcdcaa",
            "isprintable": "#dcdcaa",
            "isspace": "#dcdcaa",
            "istitle": "#dcdcaa",
            "isupper": "#dcdcaa",
            "join": "#dcdcaa",
            "ljust": "#dcdcaa",
            "lower": "#dcdcaa",
            "lstrip": "#dcdcaa",
            "maketrans": "#dcdcaa",
            "partition": "#dcdcaa",
            "removeprefix": "#dcdcaa",
            "removesuffix": "#dcdcaa",
            "replace": "#dcdcaa",
            "rfind": "#dcdcaa",
            "rindex": "#dcdcaa",
            "rjust": "#dcdcaa",
            "rpartition": "#dcdcaa",
            "rsplit": "#dcdcaa",
            "rstrip": "#dcdcaa",
            "split": "#dcdcaa",
            "splitlines": "#dcdcaa",
            "startswith": "#dcdcaa",
            "strip": "#dcdcaa",
            "swapcase": "#dcdcaa",
            "title": "#dcdcaa",
            "translate": "#dcdcaa",
            "upper": "#dcdcaa",
            "zfill": "#dcdcaa",
            "decode": "#dcdcaa",
            "fromhex": "#dcdcaa",
            "append": "#dcdcaa",
            "extend": "#dcdcaa",
            "insert": "#dcdcaa",
            "remove": "#dcdcaa",
            "pop": "#dcdcaa",
            "clear": "#dcdcaa",
            "sort": "#dcdcaa",
            "reverse": "#dcdcaa",
            "copy": "#dcdcaa",
            "keys": "#dcdcaa",
            "values": "#dcdcaa",
            "items": "#dcdcaa",
            "get": "#dcdcaa",
            "setdefault": "#dcdcaa",
            "update": "#dcdcaa",
            "popitem": "#dcdcaa",
            "fromkeys": "#dcdcaa",
            "add": "#dcdcaa",
            "discard": "#dcdcaa",
            "union": "#dcdcaa",
            "intersection": "#dcdcaa",
            "difference": "#dcdcaa",
            "symmetric_difference": "#dcdcaa",
            "intersection_update": "#dcdcaa",
            "difference_update": "#dcdcaa",
            "symmetric_difference_update": "#dcdcaa",
            "issubset": "#dcdcaa",
            "issuperset": "#dcdcaa",
            "isdisjoint": "#dcdcaa",
            "bit_length": "#dcdcaa",
            "bit_count": "#dcdcaa",
            "to_bytes": "#dcdcaa",
            "from_bytes": "#dcdcaa",
            "as_integer_ratio": "#dcdcaa",
            "is_integer": "#dcdcaa",
            "conjugate": "#dcdcaa",
            "real": "#dcdcaa",
            "imag": "#dcdcaa",
            "numerator": "#dcdcaa",
            "denominator": "#dcdcaa",
            "read": "#dcdcaa",
            "readline": "#dcdcaa",
            "readlines": "#dcdcaa",
            "write": "#dcdcaa",
            "writelines": "#dcdcaa",
            "close": "#dcdcaa",
            "seek": "#dcdcaa",
            "tell": "#dcdcaa",
            "flush": "#dcdcaa",
            "truncate": "#dcdcaa",
            "fileno": "#dcdcaa",
            "detach": "#dcdcaa",
            "readable": "#dcdcaa",
            "writable": "#dcdcaa",
            "seekable": "#dcdcaa",
            "isatty": "#dcdcaa",
            "closed": "#dcdcaa",
            "mode": "#dcdcaa",
            "name": "#dcdcaa",
            "buffer": "#dcdcaa",
            "abstractmethod": "#dcdcaa",
            "cached_property": "#dcdcaa",
            "dataclass": "#dcdcaa",
            "contextmanager": "#dcdcaa",
            "asynccontextmanager": "#dcdcaa",
            "wraps": "#dcdcaa",
            "lru_cache": "#dcdcaa",
            "cache": "#dcdcaa",
            "singledispatch": "#dcdcaa",
            "total_ordering": "#dcdcaa",
            "overload": "#dcdcaa",
            "final": "#dcdcaa",
            "override": "#dcdcaa",
            "setter": "#dcdcaa",
            "getter": "#dcdcaa",
            "deleter": "#dcdcaa",
            "field": "#dcdcaa",
            "run": "#dcdcaa",
            "start": "#dcdcaa",
            "sleep": "#dcdcaa",
            "gather": "#dcdcaa",
            "create_task": "#dcdcaa",
            "wait": "#dcdcaa",
            "wait_for": "#dcdcaa",
            "ensure_future": "#dcdcaa",
            "get_event_loop": "#dcdcaa",
            "new_event_loop": "#dcdcaa",
            "set_event_loop": "#dcdcaa",
            "run_until_complete": "#dcdcaa",
            "run_forever": "#dcdcaa",
            "run_in_executor": "#dcdcaa",
            "call_soon": "#dcdcaa",
            "call_later": "#dcdcaa",
            "acquire": "#dcdcaa",
            "release": "#dcdcaa",
            "notify": "#dcdcaa",
            "notify_all": "#dcdcaa",
            "is_set": "#dcdcaa",
            "is_alive": "#dcdcaa",
            "cancel": "#dcdcaa",
            "done": "#dcdcaa",
            "result": "#dcdcaa",
            "exception": "#dcdcaa",
            "submit": "#dcdcaa",
            "shutdown": "#dcdcaa",
            "send": "#dcdcaa",
            "throw": "#dcdcaa",
            "close_connection": "#dcdcaa",
            "connect": "#dcdcaa",
            "cursor": "#dcdcaa",
            "commit": "#dcdcaa",
            "rollback": "#dcdcaa",
            "execute": "#dcdcaa",
            "executemany": "#dcdcaa",
            "fetchone": "#dcdcaa",
            "fetchall": "#dcdcaa",
            "fetchmany": "#dcdcaa",
            "dumps": "#dcdcaa",
            "loads": "#dcdcaa",
            "dump": "#dcdcaa",
            "load": "#dcdcaa",
            "search": "#dcdcaa",
            "fullmatch": "#dcdcaa",
            "sub": "#dcdcaa",
            "subn": "#dcdcaa",
            "findall": "#dcdcaa",
            "finditer": "#dcdcaa",
            "compile_pattern": "#dcdcaa",
            "group": "#dcdcaa",
            "groups": "#dcdcaa",
            "groupdict": "#dcdcaa",
            "span": "#dcdcaa",
            "expand": "#dcdcaa",
            "escape": "#dcdcaa",
            "exists": "#dcdcaa",
            "isfile": "#dcdcaa",
            "isdir": "#dcdcaa",
            "listdir": "#dcdcaa",
            "makedirs": "#dcdcaa",
            "mkdir": "#dcdcaa",
            "rmdir": "#dcdcaa",
            "rename": "#dcdcaa",
            "walk": "#dcdcaa",
            "abspath": "#dcdcaa",
            "basename": "#dcdcaa",
            "dirname": "#dcdcaa",
            "splitext": "#dcdcaa",
            "getsize": "#dcdcaa",
            "getcwd": "#dcdcaa",
            "chdir": "#dcdcaa",
            "system": "#dcdcaa",
            "getenv": "#dcdcaa",
            "putenv": "#dcdcaa",
            "urandom": "#dcdcaa",
            "now": "#dcdcaa",
            "today": "#dcdcaa",
            "utcnow": "#dcdcaa",
            "strftime": "#dcdcaa",
            "strptime": "#dcdcaa",
            "timestamp": "#dcdcaa",
            "date": "#dcdcaa",
            "time": "#dcdcaa",
            "weekday": "#dcdcaa",
            "isoformat": "#dcdcaa",
            "randint": "#dcdcaa",
            "choice": "#dcdcaa",
            "choices": "#dcdcaa",
            "shuffle": "#dcdcaa",
            "sample": "#dcdcaa",
            "uniform": "#dcdcaa",
            "randrange": "#dcdcaa",
            "deepcopy": "#dcdcaa",
            "sqrt": "#dcdcaa",
            "floor": "#dcdcaa",
            "ceil": "#dcdcaa",
            "log": "#dcdcaa",
            "log2": "#dcdcaa",
            "log10": "#dcdcaa",
            "sin": "#dcdcaa",
            "cos": "#dcdcaa",
            "tan": "#dcdcaa",
            "atan2": "#dcdcaa",
            "degrees": "#dcdcaa",
            "radians": "#dcdcaa",
            "factorial": "#dcdcaa",
            "gcd": "#dcdcaa",
            "isnan": "#dcdcaa",
            "isinf": "#dcdcaa",
            "debug": "#dcdcaa",
            "info": "#dcdcaa",
            "warning": "#dcdcaa",
            "error": "#dcdcaa",
            "critical": "#dcdcaa",
            "basicConfig": "#dcdcaa",
            "getLogger": "#dcdcaa",
            "exception_handler": "#dcdcaa",
            "add_argument": "#dcdcaa",
            "parse_args": "#dcdcaa",
            "add_parser": "#dcdcaa",
            "check_output": "#dcdcaa",
            "check_call": "#dcdcaa",
            "Popen": "#dcdcaa",
            "communicate": "#dcdcaa",
            "terminate": "#dcdcaa",
            "kill": "#dcdcaa",
            "poll": "#dcdcaa",
            "os": "#4ec9b0",
            "sys": "#4ec9b0",
            "re": "#4ec9b0",
            "json": "#4ec9b0",
            "math": "#4ec9b0",
            "random": "#4ec9b0",
            "datetime": "#4ec9b0",
            "asyncio": "#4ec9b0",
            "threading": "#4ec9b0",
            "subprocess": "#4ec9b0",
            "logging": "#4ec9b0",
            "pathlib": "#4ec9b0",
            "typing": "#4ec9b0",
            "itertools": "#4ec9b0",
            "functools": "#4ec9b0",
            "collections": "#4ec9b0",
            "dataclasses": "#4ec9b0",
            "enum": "#4ec9b0",
            "abc": "#4ec9b0",
            "io": "#4ec9b0",
            "csv": "#4ec9b0",
            "sqlite3": "#4ec9b0",
            "socket": "#4ec9b0",
            "struct": "#4ec9b0",
            "hashlib": "#4ec9b0",
            "base64": "#4ec9b0",
            "uuid": "#4ec9b0",
            "shutil": "#4ec9b0",
            "glob": "#4ec9b0",
            "argparse": "#4ec9b0",
            "traceback": "#4ec9b0",
            "warnings": "#4ec9b0",
            "pickle": "#4ec9b0",
            "string": "#4ec9b0",
            "textwrap": "#4ec9b0",
            "unittest": "#4ec9b0",
            "requests": "#4ec9b0",
            "numpy": "#4ec9b0",
            "cv2": "#4ec9b0",
            "pandas": "#4ec9b0",
            "Thread": "#4ec9b0",
            "Lock": "#4ec9b0",
            "Event": "#4ec9b0",
            "Queue": "#4ec9b0",
            "Path": "#4ec9b0",
            "Enum": "#4ec9b0",
            "Any": "#4ec9b0",
            "Optional": "#4ec9b0",
            "Union": "#4ec9b0",
            "List": "#4ec9b0",
            "Dict": "#4ec9b0",
            "Tuple": "#4ec9b0",
            "Set": "#4ec9b0",
            "Callable": "#4ec9b0",
            "Iterable": "#4ec9b0",
            "Iterator": "#4ec9b0",
            "Generator": "#4ec9b0",
            "Awaitable": "#4ec9b0",
            "Coroutine": "#4ec9b0",
            "TypeVar": "#4ec9b0",
            "Literal": "#4ec9b0",
            "Final": "#4ec9b0",
            "ClassVar": "#4ec9b0",
            "Protocol": "#4ec9b0",
            "NamedTuple": "#4ec9b0",
            "TypedDict": "#4ec9b0",
            "defaultdict": "#4ec9b0",
            "OrderedDict": "#4ec9b0",
            "Counter": "#4ec9b0",
            "deque": "#4ec9b0",
            "namedtuple": "#4ec9b0"
        }
    },
    "DarsHa": {
        "Dars1": {
            "name": {"English": "Getting Started", "فارسی": "شروع کار", "کوردی": "دەستپێکردن"},
            "Lessons": {
                "Lesson1": {
                    "id": "start_1",
                    "Title": {"English": "Intro to Python", "فارسی": "آشنایی با پایتون", "کوردی": "ئاشنابوون بە پایتۆن"},
                    "Tozihat": {"English": "Python is a powerful programming language\nused for web, AI, and game development.\nCode executes line by line.", "فارسی": "پایتون یک زبان برنامه‌نویسی قدرتمند است\nکه برای وب، هوش مصنوعی و بازی‌سازی\nاستفاده می‌شود کدها خط به خط اجرا می‌شوند", "کوردی": "پایتۆن زمانێکی بەهێزی بەرنامەسازییە\nبۆ وێب، ژیری دەستکرد و دروستکردنی یاری بەکاردێت.\nکۆدەکان دێڕ بە دێڕ جێبەجێ دەکرێن."},
                    "ZirTozihat": {"English": "Click the Run button to execute your code.", "فارسی": "برای اجرای کد روی دکمه اجرای کد بزن\nو خروجی را ببین", "کوردی": "بۆ جێبەجێکردنی کۆدەکە کرتە لە جێبەجێکردن بکە."},
                    "Code": {"English": "print(\"Hello Python World\")", "فارسی": "print(\"سلام دنیای پایتون\")", "کوردی": "print(\"سڵاو جیهانی پایتۆن\")"},
                    "challenge": {"question": {"English": "Hint: You need to use the print function. For example, write: print('I love Python')", "فارسی": "راهنمایی: برای این کار باید از تابع زیر استفاده کنی:\nprint('I love Python')\nآن را بنویس و اجرا کن.", "کوردی": "ڕێنمایی: بۆ ئەم کارە دەبێت ئەم فانکشنە بەکاربهێنیت:\nprint('I love Python')\nبینووسە و جێبەجێی بکە."}, "type": "contains", "expected": {"English": ["Python"], "فارسی": ["Python"], "کوردی": ["Python"]}, "must_include": ["print"], "points": 10}
                },
                "Lesson2": {
                    "id": "start_2",
                    "Title": {"English": "Code Structure", "فارسی": "ساختار نوشتاری کد", "کوردی": "پێکهاتەی کۆد"},
                    "Tozihat": {"English": "Each line of code is a command.\nPython does not need semicolons.\nKeep code clean and readable.", "فارسی": "هر خط کد یک دستور است پایتون\nبه سمی‌کالن نیاز ندارد و ساختار کد\nباید تمیز و خوانا باشد", "کوردی": "هەر دێڕێکی کۆد فەرمانێکە.\nپایتۆن پێویستی بە فاریزەی خاڵدار نییە.\nپێویستە کۆدەکە پاک و ڕوون بێت."},
                    "ZirTozihat": {"English": "Write each command on a new line.", "فارسی": "هر دستور را در یک خط جدا بنویس", "کوردی": "هەر فەرمانێک لە دێڕێکی جیاوازدا بنووسە."},
                    "Code": {"English": "print(\"Line one\")\nprint(\"Line two\")", "فارسی": "print(\"خط اول\")\nprint(\"خط دوم\")", "کوردی": "print(\"دێڕی یەکەم\")\nprint(\"دێڕی دووەم\")"},
                    "challenge": {"question": {"English": "Hint: Just use the print command twice. Like print('Hello') on line one and print('World') on line two.", "فارسی": "راهنمایی: فقط کافیه دو بار زیر هم از دستور چاپ استفاده کنی:\nprint('Hello')\nprint('World')", "کوردی": "ڕێنمایی: تەنها پێویستە دوو جار فەرمانی چاپکردن لەسەر یەک بەکاربهێنیت:\nprint('Hello')\nprint('World')"}, "type": "contains", "expected": {"English": ["Line one", "Line two"], "فارسی": ["خط اول", "خط دوم"], "کوردی": ["دێڕی یەکەم", "دێڕی دووەم"]}, "must_include": ["print"], "points": 10}
                },
                "Lesson3": {
                    "id": "start_3",
                    "Title": {"English": "Indentation", "فارسی": "تورفتگی کدها", "کوردی": "بۆشایی دانانی کۆدەکان"},
                    "Tozihat": {"English": "Python uses indentation to define code blocks.\nCorrect indentation is mandatory.", "فارسی": "پایتون برای مشخص کردن بلوک‌های کد\nاز تورفتگی (فاصله) استفاده می‌کند\nرعایت تورفتگی اجباری است", "کوردی": "پایتۆن بۆشایی بەکاردەهێنێت بۆ دیاریکردنی بەشەکانی کۆد.\nدانانی بۆشایی پێویستە."},
                    "ZirTozihat": {"English": "Use 4 spaces for indentation.", "فارسی": "معمولا از ۴ فاصله برای تورفتگی استفاده می‌شود", "کوردی": "بەگشتی ٤ بۆشایی بۆ داخڵبوون بەکاردەهێنرێت."},
                    "Code": {"English": "if 8 > 7:\n    print(\"Correct\")", "فارسی": "if 8 > 7:\n    print(\"تورفتگی درست است\")", "کوردی": "if 8 > 7:\n    print(\"بۆشاییەکە دروستە\")"},
                    "challenge": {"question": {"English": "Hint: Write the condition like if 10 > 5: then go to the next line, add 4 spaces and type print('Correct')", "فارسی": "راهنمایی: اول شرط رو بنویس:\nif 10 > 5:\nبعد برو خط بعد، ۴ تا اسپیس بزن و بنویس:\nprint('Correct')", "کوردی": "ڕێنمایی: یەکەمجار مەرجەکە بنووسە:\nif 10 > 5:\nپاشان بڕۆ دێڕی داهاتوو، ٤ بۆشایی دابنێ و بنووسە:\nprint('Correct')"}, "type": "contains", "expected": {"English": ["Correct"], "فارسی": ["درست"], "کوردی": ["دروستە"]}, "must_include": ["if"], "points": 10}
                },
                "Lesson4": {
                    "id": "start_4",
                    "Title": {"English": "Writing Statements", "فارسی": "نوشتن دستورات", "کوردی": "نووسینی فەرمانەکان"},
                    "Tozihat": {"English": "A line of code that does something is a statement.\nPrograms consist of multiple statements.", "فارسی": "هر خط کد که کاری انجام می‌دهد\nیک دستور نامیده می‌شود یک برنامه\nاز چندین دستور تشکیل شده است", "کوردی": "هەر دێڕێک کە کارێک دەکات پێی دەوترێت فەرمان.\nبەرنامەیەک لە چەندین فەرمان پێکدێت."},
                    "ZirTozihat": {"English": "You can write multiple statements sequentially.", "فارسی": "می‌توانی چند دستور مختلف را پشت سر هم بنویسی", "کوردی": "دەتوانیت چەندین فەرمان لەسەر یەک بنووسیت."},
                    "Code": {"English": "x = 5\ny = 10\nprint(x + y)", "فارسی": "x = 5\ny = 10\nprint(x + y)", "کوردی": "x = 5\ny = 10\nprint(x + y)"},
                    "challenge": {"question": {"English": "Hint: On line one write a = 10, line two b = 5, and line three print(a + b) to add them.", "فارسی": "راهنمایی: تو خط اول بنویس:\na = 10\nتو خط دوم:\nb = 5\nو تو خط سوم برای جمع بنویس:\nprint(a + b)", "کوردی": "ڕێنمایی: لە دێڕی یەکەم بنووسە:\na = 10\nلە دێڕی دووەم:\nb = 5\nوە لە دێڕی سێیەم بۆ کۆکردنەوەیان بنووسە:\nprint(a + b)"}, "type": "contains", "expected": {"English": ["15"], "فارسی": ["15"], "کوردی": ["15"]}, "must_include": ["=", "+", "print"], "points": 10}
                },
                "Lesson5": {
                    "id": "start_5",
                    "Title": {"English": "Printing Strings and Numbers", "فارسی": "چاپ رشته و اعداد", "کوردی": "چاپکردنی دەق و ژمارەکان"},
                    "Tozihat": {"English": "The `print` function displays text and numbers on the screen.", "فارسی": "با تابع\nprint\nمی‌توان هم متن و هم عدد\nرا روی خروجی صفحه نمایش داد", "کوردی": "بە هۆی فانکشنی\nprint\nدەتوانیت دەق و ژمارە لەسەر شاشە نیشان بدەیت."},
                    "ZirTozihat": {"English": "Use quotes for strings, none for numbers.", "فارسی": "رشته‌ها را داخل گیومه بنویس\nاعداد را بدون گیومه", "کوردی": "دەقەکان لەناو کەوانە دابنێ، ژمارەکان بێ کەوانە."},
                    "Code": {"English": "print(\"My Age\")\nprint(20)", "فارسی": "print(\"سن من\")\nprint(20)", "کوردی": "print(\"تەمەنی من\")\nprint(20)"},
                    "challenge": {"question": {"English": "Hint: Write print with quotes for text like print('Name'), and on the next line without quotes for a number like print(16)", "فارسی": "راهنمایی: یه بار چاپ رو با کوتیشن برای متن بنویس:\nprint('Name')\nو تو خط بعد بدون کوتیشن برای یه عدد بنویس:\nprint(16)", "کوردی": "ڕێنمایی: جارێک چاپکردن بە کەوانە بۆ دەق بنووسە:\nprint('Name')\nوە لە دێڕی داهاتوو بێ کەوانە بۆ ژمارە بنووسە:\nprint(16)"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["print"], "points": 5}
                }
            }
        },
        "Dars2": {
            "name": {"English": "Variables and Data", "فارسی": "متغیرها و داده‌ها", "کوردی": "گۆڕاوەکان و دراوەکان"},
            "Lessons": {
                "Lesson1": {
                    "id": "var_1",
                    "Title": {"English": "What is a Variable?", "فارسی": "متغیر چیست؟", "کوردی": "گۆڕاو چییە؟"},
                    "Tozihat": {"English": "Variables store data.\nNo type declaration is needed.\nAssign using the `=` sign.", "فارسی": "متغیر محلی از حافظه برای ذخیره داده است\nبرای ایجاد متغیر نیازی به تعیین نوع نیست\nو مقداردهی با علامت\n=\nانجام می‌شود", "کوردی": "گۆڕاو شوێنێکە بۆ هەڵگرتنی دراوە.\nپێویست بە دیاریکردنی جۆر ناکات.\nبە نیشانەی `=` بەها دەدرێتێ."},
                    "ZirTozihat": {"English": "Variable name goes on the left.", "فارسی": "نام متغیر در سمت چپ نوشته می‌شود", "کوردی": "ناوی گۆڕاوەکە لە لای چەپ دەنووسرێت."},
                    "Code": {"English": "name = \"Ramyar\"\nnum = 55\nprint(name, num)", "فارسی": "name = \"Ramyar\"\nnum = 55\nprint(name, num)", "کوردی": "name = \"Ramyar\"\nnum = 55\nprint(name, num)"},
                    "challenge": {"question": {"English": "Hint: Name a variable my_name and set it to your name. Then print it using print(my_name).", "فارسی": "راهنمایی: اسم متغیر رو بذار:\nmy_name = 'Ali'\nبعد با دستور زیر چاپش کن:\nprint(my_name)", "کوردی": "ڕێنمایی: ناوی گۆڕاوەکە بنێ:\nmy_name = 'Ali'\nپاشان بەم فەرمانە چاپی بکە:\nprint(my_name)"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["=", "print"], "points": 10}
                },
                "Lesson2": {
                    "id": "var_2",
                    "Title": {"English": "Data Types", "فارسی": "انواع داده", "کوردی": "جۆرەکانی دراوە"},
                    "Tozihat": {"English": "Data comes in different types: strings, integers, floats.\nThe `type` function reveals the type.", "فارسی": "داده‌ها انواع مختلفی دارند رشته (متن)\nعدد صحیح (بدون اعشار) و عدد اعشاری\nتابع\ntype\nنوع داده را نشان می‌دهد", "کوردی": "دراوەکان جۆری جیاوازیان هەیە: دەق، ژمارەی تەواو، ژمارەی کەرت.\nفانکشنی `type` جۆرەکە پیشان دەدات."},
                    "ZirTozihat": {"English": "Use quotes for text data.", "فارسی": "برای متن از کوتیشن استفاده کنید", "کوردی": "بۆ دەق کەوانە بەکاربهێنە."},
                    "Code": {"English": "age = 18\nheight = 1.75\ncity = 'NewYork'\nprint(type(age))", "فارسی": "age = 18\nheight = 1.75\ncity = 'NewYork'\nprint(type(age))", "کوردی": "age = 18\nheight = 1.75\ncity = 'NewYork'\nprint(type(age))"},
                    "challenge": {"question": {"English": "Hint: Make a float variable like x = 2.5, then use print(type(x)) to see the word float in output.", "فارسی": "راهنمایی: یه عدد اعشاری بساز:\nx = 2.5\nو بعد نوعش رو چاپ کن:\nprint(type(x))", "کوردی": "ڕێنمایی: ژمارەیەکی کەرت دروست بکە:\nx = 2.5\nپاشان جۆرەکەی چاپ بکە:\nprint(type(x))"}, "type": "contains", "expected": {"English": ["float"], "فارسی": ["float"], "کوردی": ["float"]}, "must_include": ["type("], "points": 10}
                },
                "Lesson3": {
                    "id": "var_3",
                    "Title": {"English": "Operators", "فارسی": "عملگرها", "کوردی": "پێکهێنەرەکان"},
                    "Tozihat": {"English": "Math operators include `+`, `-`, `*`, `/`.\nThe `+` can also concatenate strings.", "فارسی": "عملگرهای ریاضی شامل جمع\n+\nو تفریق\n-\nو ضرب\n*\nو تقسیم\n/\nهستند عملگر جمع\nمی‌تواند دو رشته را هم متصل کند", "کوردی": "پێکهێنەرە بیرکارییەکان بریتین لە `+`, `-`, `*`, `/`.\nنیشانەی `+` دەتوانێت دوو دەقیش پێکەوە ببەستێتەوە."},
                    "ZirTozihat": {"English": "You can add variables together.", "فارسی": "می‌توانید متغیرها را با هم جمع کنید", "کوردی": "دەتوانیت گۆڕاوەکان پێکەوە کۆبکەیتەوە."},
                    "Code": {"English": "a = 10\nb = 20\nprint(a + b)\n\nfname = 'ali'\nlname = 'reza'\nprint(fname + lname)", "فارسی": "a = 10\nb = 20\nprint(a + b)\n\nfname = 'ali'\nlname = 'reza'\nprint(fname + lname)", "کوردی": "a = 10\nb = 20\nprint(a + b)\n\nfname = 'ali'\nlname = 'reza'\nprint(fname + lname)"},
                    "challenge": {"question": {"English": "Hint: Create two variables like t1 = 'Hi ' and t2 = 'Ali', then print them together using + like print(t1 + t2)", "فارسی": "راهنمایی: دو تا متغیر بساز:\nt1 = 'Hi '\nt2 = 'Ali'\nو بعد جفتشون رو با علامت جمع چاپ کن:\nprint(t1 + t2)", "کوردی": "ڕێنمایی: دوو گۆڕاو دروست بکە:\nt1 = 'Hi '\nt2 = 'Ali'\nپاشان بە نیشانەی کۆکردنەوە پێکەوە چاپیان بکە:\nprint(t1 + t2)"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["=", "+"], "points": 10}
                },
                "Lesson4": {
                    "id": "var_4",
                    "Title": {"English": "Getting Input", "فارسی": "دریافت ورودی", "کوردی": "وەرگرتنی زانیاری"},
                    "Tozihat": {"English": "The `input` command gets user data.\nIt always returns a string.", "فارسی": "با دستور\ninput\nمی‌توانیم داده‌ها را\nاز کاربر بگیریم این دستور همیشه داده‌ها\nرا به صورت رشته دریافت می‌کند", "کوردی": "بە فەرمانی `input` دەتوانین زانیاری لە بەکارهێنەر وەربگرین.\nهەمیشە وەک دەق دەیگەڕێنێتەوە."},
                    "ZirTozihat": {"English": "Provide a prompt message inside the parentheses.", "فارسی": "یک پیام راهنما داخل پرانتز بنویسید", "کوردی": "پەیامێکی ڕێنمایی لەناو کەوانەکان بنووسە."},
                    "Code": {"English": "name = input('Enter your name: ')\nprint('Welcome', name)", "فارسی": "name = input('Enter your name: ')\nprint('Welcome', name)", "کوردی": "name = input('Enter your name: ')\nprint('Welcome', name)"},
                    "challenge": {"question": {"English": "Hint: Make a variable equal to input('Name: '). Then print it like print('Welcome', variable_name).", "فارسی": "راهنمایی: متغیری بساز و برابر ورودی قرار بده:\nname = input('Name: ')\nبعد تو پرینت بنویس:\nprint('Welcome', name)", "کوردی": "ڕێنمایی: گۆڕاوێک دروست بکە و یەکسانی بکە بە ورودی:\nname = input('Name: ')\nپاشان لە چاپکردنەکەدا بنووسە:\nprint('Welcome', name)"}, "type": "contains", "expected": {"English": ["Welcome"], "فارسی": ["Welcome"], "کوردی": ["Welcome"]}, "must_include": ["input("], "points": 10}
                },
                "Lesson5": {
                    "id": "var_5",
                    "Title": {"English": "Type Casting", "فارسی": "تبدیل نوع داده", "کوردی": "گۆڕینی جۆری دراوە"},
                    "Tozihat": {"English": "Use `int()` and `float()` to cast strings to numbers for math operations.", "فارسی": "برای محاسبات ریاضی باید رشته را به عدد\nتبدیل کنیم از تابع\nint\nبرای اعداد صحیح\nو تابع\nfloat\nبرای اعشار استفاده می‌شود", "کوردی": "بۆ کرداری بیرکاری دەبێت دەق بگۆڕین بۆ ژمارە.\nفانکشنی `int` بۆ ژمارەی تەواو و `float` بۆ کەرت بەکاردێت."},
                    "ZirTozihat": {"English": "Use `str()` to cast back to text.", "فارسی": "تابع\nstr\nبرای تبدیل عدد به متن استفاده می‌شود", "کوردی": "فانکشنی `str` بۆ گۆڕینەوە بۆ دەق بەکاردێت."},
                    "Code": {"English": "year = int(input('Enter birth year: '))\nage = 2024 - year\nprint('Your age: ' + str(age))", "فارسی": "year = int(input('Enter birth year: '))\nage = 1403 - year\nprint('Your age: ' + str(age))", "کوردی": "year = int(input('Enter birth year: '))\nage = 2024 - year\nprint('Your age: ' + str(age))"},
                    "challenge": {"question": {"English": "Hint: Convert the input to int first like n = int(input()). Then on the next line print(n + 10).", "فارسی": "راهنمایی: اول ورودی رو به عدد تبدیل کن:\nn = int(input())\nبعد تو خط بعدی پرینت کن:\nprint(n + 10)", "کوردی": "ڕێنمایی: سەرەتا زانیارییەکە بگۆڕە بۆ ژمارە:\nn = int(input())\nپاشان لە دێڕی داهاتوو چاپ بکە:\nprint(n + 10)"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["int(", "+", "10"], "points": 15}
                }
            }
        },
        "Dars3": {
            "name": {"English": "Conditions", "فارسی": "ساختارهای شرطی", "کوردی": "پێکهاتە مەرجدارەکان"},
            "Lessons": {
                "Lesson1": {
                    "id": "cond_1",
                    "Title": {"English": "If Statements & Comparisons", "فارسی": "دستور شرطی و مقایسه", "کوردی": "فەرمانی مەرجدار و بەراوردکردن"},
                    "Tozihat": {"English": "Use `if` for decisions. Operators include `==`, `!=`, `>`, `<`.", "فارسی": "دستور\nif\nبرای تصمیم‌گیری استفاده می‌شود\nعملگرهای مقایسه‌ای شامل مساوی\n==\nو نامساوی\n!=\nو بزرگتر\n>\nو کوچکتر\n<\nهستند", "کوردی": "فەرمانی `if` بۆ بڕیاردان بەکاردێت.\nنیشانەکانی بەراورد بریتین لە `==`, `!=`, `>`, `<`."},
                    "ZirTozihat": {"English": "Remember the colon after the condition.", "فارسی": "دقت کنید بعد از شرط باید علامت دونقطه بگذارید", "کوردی": "لەبیرت بێت دوای مەرجەکە دوو خاڵ دابنێیت."},
                    "Code": {"English": "price = 120\nif price != 100:\n    print('price is not true')", "فارسی": "price = 120\nif price != 100:\n    print('price is not true')", "کوردی": "price = 120\nif price != 100:\n    print('price is not true')"},
                    "challenge": {"question": {"English": "Hint: Just write if 10 > 5: and on the next line with 4 spaces type print('yes')", "فارسی": "راهنمایی: دقیقا بنویس:\nif 10 > 5:\nو تو خط بعد با ۴ تا فاصله بنویس:\nprint('yes')", "کوردی": "ڕێنمایی: تەنها بنووسە:\nif 10 > 5:\nوە لە دێڕی داهاتوو بە ٤ بۆشاییەوە بنووسە:\nprint('yes')"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["if", ">", "10", "5"], "points": 10}
                },
                "Lesson2": {
                    "id": "cond_2",
                    "Title": {"English": "Logical Operators", "فارسی": "عملگرهای منطقی", "کوردی": "پێکهێنەرە لۆژیکییەکان"},
                    "Tozihat": {"English": "`and`, `or`, and `not` allow you to combine conditions.", "فارسی": "عملگر\nand\nوقتی درست است که هر دو شرط درست باشند\nعملگر\nor\nوقتی درست است که حداقل یکی درست باشد\nعملگر\nnot\nشرط را برعکس می‌کند", "کوردی": "`and`, `or`, وە `not` ڕێگەت پێدەدەن مەرجەکان تێکەڵ بکەیت."},
                    "ZirTozihat": {"English": "Conditions can be chained.", "فارسی": "می‌توان شروط را ترکیب کرد", "کوردی": "دەکرێت مەرجەکان بەیەکەوە ببەسترێنەوە."},
                    "Code": {"English": "day = 'Friday'\nif day == 'Friday' or day == 'Thursday':\n    print('Holiday')", "فارسی": "day = 'Friday'\nif day == 'Friday' or day == 'Thursday':\n    print('Holiday')", "کوردی": "day = 'Friday'\nif day == 'Friday' or day == 'Thursday':\n    print('Holiday')"},
                    "challenge": {"question": {"English": "Hint: Join conditions with and. Like if 5 > 2 and 10 > 3: followed by a simple print on the next line.", "فارسی": "راهنمایی: شرطت رو وصل کن:\nif 5 > 2 and 10 > 3:\nبعد تو خط بعد یه پرینت ساده بذار:\nprint('ok')", "کوردی": "ڕێنمایی: مەرجەکان ببەستەوە:\nif 5 > 2 and 10 > 3:\nپاشان چاپێکی سادە دابنێ:\nprint('ok')"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["if", "and"], "points": 10}
                },
                "Lesson3": {
                    "id": "cond_3",
                    "Title": {"English": "If-Else Structure", "فارسی": "ساختار شرطی دومرحله‌ای", "کوردی": "پێکهاتەی مەرجی دوو قۆناغی"},
                    "Tozihat": {"English": "The `else` block runs if the `if` condition is false.", "فارسی": "اگر شرط دستور\nif\nدرست نباشد\nکدهای داخل بلوک\nelse\nاجرا می‌شوند\nبخش\nelse\nنیازی به شرط ندارد", "کوردی": "بەشی `else` جێبەجێ دەبێت ئەگەر مەرجی `if` هەڵە بێت."},
                    "ZirTozihat": {"English": "Colons are required for else too.", "فارسی": "برای بلوک دوم نیز علامت دونقطه الزامی است", "کوردی": "دوو خاڵ بۆ بەشی دووەمیش پێویستە."},
                    "Code": {"English": "number = 8\nif number > 0 and number < 10:\n    print('valid')\nelse:\n    print('not valid')", "فارسی": "number = 8\nif number > 0 and number < 10:\n    print('valid')\nelse:\n    print('not valid')", "کوردی": "number = 8\nif number > 0 and number < 10:\n    print('valid')\nelse:\n    print('not valid')"},
                    "challenge": {"question": {"English": "Hint: Make x = 4. Check if x % 2 == 0: to print even, and in the else block print odd.", "فارسی": "راهنمایی: یه متغیر بساز:\nx = 4\nاگه باقی‌مانده تقسیمش بر ۲ صفر بود:\nif x % 2 == 0:\nدر بخش بعدی پرینت کن:\nelse:", "کوردی": "ڕێنمایی: گۆڕاوێک دروست بکە:\nx = 4\nبپشکنە ئەگەر:\nif x % 2 == 0:\nلە بەشی داهاتوو چاپ بکە:\nelse:"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["if", "else", "%", "2"], "points": 10}
                },
                "Lesson4": {
                    "id": "cond_4",
                    "Title": {"English": "Multiple Conditions", "فارسی": "بررسی چند شرط", "کوردی": "پشکنینی چەند مەرجێک"},
                    "Tozihat": {"English": "Use `elif` to check multiple conditions sequentially.", "فارسی": "برای بررسی چندین شرط مختلف از دستور\nelif\nاستفاده می‌شود فقط اولین شرطی\nکه صحیح باشد اجرا می‌گردد", "کوردی": "بەکاربهێنە `elif` بۆ پشکنینی چەند مەرجێک لەسەر یەک."},
                    "ZirTozihat": {"English": "Order of conditions matters.", "فارسی": "ترتیب نوشتن شروط مهم است", "کوردی": "ڕیزبەندی مەرجەکان گرنگە."},
                    "Code": {"English": "level = 'medium'\nif level == 'easy':\n    print('Game is easy')\nelif level == 'medium':\n    print('Game is normal')\nelse:\n    print('Game is hard')", "فارسی": "level = 'medium'\nif level == 'easy':\n    print('Game is easy')\nelif level == 'medium':\n    print('Game is normal')\nelse:\n    print('Game is hard')", "کوردی": "level = 'medium'\nif level == 'easy':\n    print('Game is easy')\nelif level == 'medium':\n    print('Game is normal')\nelse:\n    print('Game is hard')"},
                    "challenge": {"question": {"English": "Hint: Set x = 10. Check if x > 10, elif x == 10, else check for smaller. Print something for each.", "فارسی": "راهنمایی: به متغیر مقدار بده:\nx = 10\nبا دستورات زیر چک کن:\nif x > 10:\nelif x == 10:\nelse:", "کوردی": "ڕێنمایی: بەها بدە بە گۆڕاوەکە:\nx = 10\nبە فەرمانەکانی خوارەوە بپشکنە:\nif x > 10:\nelif x == 10:\nelse:"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["if", "elif", "else"], "points": 15}
                }
            }
        },
        "Dars4": {
            "name": {"English": "Loops", "فارسی": "حلقه‌های تکرار", "کوردی": "بازنەکانی دووبارەبوونەوە"},
            "Lessons": {
                "Lesson1": {
                    "id": "loop_1",
                    "Title": {"English": "For Loops", "فارسی": "حلقه اول و پیمایش", "کوردی": "بازنەی یەکەم و گەڕان"},
                    "Tozihat": {"English": "`for` loops iterate over sequences like lists or strings.", "فارسی": "حلقه\nfor\nبرای تکرار اجرای دستورات\nروی یک دنباله یا لیست یا رشته\nاستفاده می‌شود", "کوردی": "بازنەی `for` بەکاردێت بۆ دووبارەبوونەوە بەسەر لیست یان دەقدا."},
                    "ZirTozihat": {"English": "Each item is placed in the loop variable.", "فارسی": "در هر تکرار یک عضو در متغیر حلقه قرار می‌گیرد", "کوردی": "لە هەر دووبارەبوونەوەیەکدا بەشێک دەچێتە ناو گۆڕاوی بازنەکەوە."},
                    "Code": {"English": "colors = ['red', 'blue', 'green']\nfor item in colors:\n    print('color:', item)", "فارسی": "colors = ['red', 'blue', 'green']\nfor item in colors:\n    print('color:', item)", "کوردی": "colors = ['red', 'blue', 'green']\nfor item in colors:\n    print('color:', item)"},
                    "challenge": {"question": {"English": "Hint: Write for letter in 'Python': and inside the loop add print(letter) to print each character.", "فارسی": "راهنمایی: خط اول رو اینطور بنویس:\nfor letter in 'Python':\nو توی حلقه پرینت کن:\nprint(letter)", "کوردی": "ڕێنمایی: دێڕی یەکەم ئاوا بنووسە:\nfor letter in 'Python':\nوە لەناو بازنەکە چاپ بکە:\nprint(letter)"}, "type": "contains", "expected": {"English": ["P", "y"], "فارسی": ["P", "y"], "کوردی": ["P", "y"]}, "must_include": ["for", "in"], "points": 10}
                },
                "Lesson2": {
                    "id": "loop_2",
                    "Title": {"English": "Range Function", "فارسی": "تولید اعداد با دامنه", "کوردی": "دروستکردنی ژمارە بە مەودا"},
                    "Tozihat": {"English": "The `range` function generates a sequence of numbers.", "فارسی": "تابع\nrange\nدنباله‌ای از اعداد تولید می‌کند\nاین تابع شامل نقطه شروع و پایان\nو همچنین گام حرکت است", "کوردی": "فانکشنی `range` زنجیرەیەک ژمارە دروست دەکات."},
                    "ZirTozihat": {"English": "The end number is not included.", "فارسی": "عدد پایانی در لیست شمرده نمی‌شود", "کوردی": "ژمارەی کۆتایی هەژمار ناکرێت."},
                    "Code": {"English": "for i in range(1, 6):\n    print(i)", "فارسی": "for i in range(1, 6):\n    print(i)", "کوردی": "for i in range(1, 6):\n    print(i)"},
                    "challenge": {"question": {"English": "Hint: The range function accepts steps! Write for i in range(0, 9, 2): and print(i).", "فارسی": "راهنمایی: توی تابع گام حرکت هم بده:\nfor i in range(0, 9, 2):\nو بعد چاپ کن:\nprint(i)", "کوردی": "ڕێنمایی: لە فانکشنەکە هەنگاو بنووسە:\nfor i in range(0, 9, 2):\nو پاشان چاپ بکە:\nprint(i)"}, "type": "contains", "expected": {"English": ["0", "8"], "فارسی": ["0", "8"], "کوردی": ["0", "8"]}, "must_include": ["for", "in", "range"], "points": 10}
                },
                "Lesson3": {
                    "id": "loop_3",
                    "Title": {"English": "Loop Control", "فارسی": "کنترل جریان حلقه", "کوردی": "کۆنتڕۆڵکردنی بازنە"},
                    "Tozihat": {"English": "`continue` skips an iteration. `break` exits the loop entirely.", "فارسی": "دستور\ncontinue\nبرای رد شدن از یک تکرار\nو دستور\nbreak\nبرای توقف کامل\nو خروج از حلقه استفاده می‌شود", "کوردی": "`continue` بازدەدات بەسەر دووبارەبوونەوەیەکدا. `break` بەتەواوی لە بازنەکە دەردەچێت."},
                    "ZirTozihat": {"English": "Usually paired with an if condition.", "فارسی": "این دستورات معمولا با یک شرط همراه هستند", "کوردی": "بەگشتی لەگەڵ مەرجێکدا بەکاردێن."},
                    "Code": {"English": "for i in range(10):\n    if i == 5:\n        break\n    print(i)", "فارسی": "for i in range(10):\n    if i == 5:\n        break\n    print(i)", "کوردی": "for i in range(10):\n    if i == 5:\n        break\n    print(i)"},
                    "challenge": {"question": {"English": "Hint: Make a loop, inside it put an if i == 3: condition followed by a break statement.", "فارسی": "راهنمایی: یه حلقه بساز، داخلش شرط بذار:\nif i == 3:\nو زیرش بنویس:\nbreak", "کوردی": "ڕێنمایی: بازنەیەک دروست بکە، لەناوی مەرجێک دابنێ:\nif i == 3:\nو لە ژێریەوە بنووسە:\nbreak"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["for", "if", "break", "3"], "points": 15}
                },
                "Lesson4": {
                    "id": "loop_4",
                    "Title": {"English": "While Loops", "فارسی": "حلقه دوم تکرار", "کوردی": "بازنەی دووەم بۆ دووبارەبوونەوە"},
                    "Tozihat": {"English": "`while` loops run as long as a condition remains true.", "فارسی": "حلقه\nwhile\nتا زمانی که شرط آن صحیح باشد\nتکرار می‌شود اگر شرط هرگز غلط نشود\nحلقه بی‌نهایت ایجاد می‌گردد", "کوردی": "بازنەی `while` بەردەوام دەبێت تا ئەو کاتەی مەرجەکە ڕاست بێت."},
                    "ZirTozihat": {"English": "Make sure the condition changes to avoid infinite loops.", "فارسی": "متغیر شرط باید حتما داخل حلقه تغییر کند", "کوردی": "دڵنیابە لە گۆڕینی مەرجەکە لەناو بازنەکەدا."},
                    "Code": {"English": "number = 5\nwhile number > 0:\n    print(number)\n    number -= 1", "فارسی": "number = 5\nwhile number > 0:\n    print(number)\n    number -= 1", "کوردی": "number = 5\nwhile number > 0:\n    print(number)\n    number -= 1"},
                    "challenge": {"question": {"English": "Hint: Make i = 1. Then write while i < 4: print it and put i = i + 1 below it to stop infinite loop.", "فارسی": "راهنمایی: متغیر بده:\ni = 1\nبعد بنویس:\nwhile i < 4:\nچاپش کن و زیرش بنویس:\ni = i + 1", "کوردی": "ڕێنمایی: بنووسە:\ni = 1\nپاشان بنووسە:\nwhile i < 4:\nچاپی بکە و دواتر دابنێ:\ni = i + 1"}, "type": "contains", "expected": {"English": ["1", "3"], "فارسی": ["1", "3"], "کوردی": ["1", "3"]}, "must_include": ["while"], "points": 15}
                }
            }
        },
        "Dars5": {
            "name": {"English": "Data Structures", "فارسی": "ساختارهای داده", "کوردی": "پێکهاتەکانی دراوە"},
            "Lessons": {
                "Lesson1": {
                    "id": "data_1",
                    "Title": {"English": "Lists", "فارسی": "لیست‌ها", "کوردی": "لیستەکان"},
                    "Tozihat": {"English": "Lists are ordered, mutable arrays created with `[]`.", "فارسی": "لیست مجموعه‌ای مرتب و قابل تغییر است\nکه با کروشه ساخته می‌شود هر عضو دارای\nشماره ایندکس است", "کوردی": "لیست کۆمەڵەیەکی ڕیزکراوە و دەتوانرێت بگۆڕدرێت. بە `[]` دروست دەکرێت."},
                    "ZirTozihat": {"English": "Add elements with `append`.", "فارسی": "با دستور\nappend\nعضو جدید اضافه می‌کنیم", "کوردی": "بە فەرمانی `append` بەشی نوێ زیاد دەکەین."},
                    "Code": {"English": "fruits = ['apple', 'banana']\nfruits.append('orange')\nfruits.pop(0)\nprint(fruits)", "فارسی": "fruits = ['apple', 'banana']\nfruits.append('orange')\nfruits.pop(0)\nprint(fruits)", "کوردی": "fruits = ['apple', 'banana']\nfruits.append('orange')\nfruits.pop(0)\nprint(fruits)"},
                    "challenge": {"question": {"English": "Hint: Make a list my_list = [1, 2, 3] and use print(my_list[1]) to print the second item (index starts at 0).", "فارسی": "راهنمایی: یه لیست بساز:\nmy_list = [1, 2, 3]\nو با این دستور عضو دوم رو چاپ کن:\nprint(my_list[1])", "کوردی": "ڕێنمایی: لیستێک دروست بکە:\nmy_list = [1, 2, 3]\nو بەم فەرمانە بەشی دووەم چاپ بکە:\nprint(my_list[1])"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["[", "]"], "points": 10}
                },
                "Lesson2": {
                    "id": "data_2",
                    "Title": {"English": "Sets", "فارسی": "مجموعه‌ها", "کوردی": "کۆمەڵەکان"},
                    "Tozihat": {"English": "Sets are unordered collections with no duplicates, using `{}`.", "فارسی": "مجموعه یا\nSet\nساختاری است که ترتیب ندارد\nعضو تکراری نمی‌پذیرد و با آکولاد\nساخته می‌شود", "کوردی": "کۆمەڵە یان Set پێکهاتەیەکە ڕیزبەندی نییە و بەشی دووبارە وەرناگرێت."},
                    "ZirTozihat": {"English": "Add items using `add`.", "فارسی": "با دستور\nadd\nعضو جدید اضافه می‌شود", "کوردی": "بە فەرمانی `add` بەشی نوێ زیاد دەکرێت."},
                    "Code": {"English": "fruitset = {'apple', 'banana'}\nfruitset.add('cherry')\nprint(fruitset)", "فارسی": "fruitset = {'apple', 'banana'}\nfruitset.add('cherry')\nprint(fruitset)", "کوردی": "fruitset = {'apple', 'banana'}\nfruitset.add('cherry')\nprint(fruitset)"},
                    "challenge": {"question": {"English": "Hint: Make a variable with braces like s = {1, 2, 2, 3} and print it to see the duplicate removed.", "فارسی": "راهنمایی: متغیری با آکولاد بساز:\ns = {1, 2, 2, 3}\nو چاپش کن تا ببینی عدد تکراری حذف میشه:\nprint(s)", "کوردی": "ڕێنمایی: گۆڕاوێک بە کەوانەی لولپێچ دروست بکە:\ns = {1, 2, 2, 3}\nو چاپی بکە بۆ بینینی لابردنی دووبارە:\nprint(s)"}, "type": "contains", "expected": {"English": ["{"], "فارسی": ["{"], "کوردی": ["{"]}, "must_include": ["{", "}"], "points": 10}
                },
                "Lesson3": {
                    "id": "data_3",
                    "Title": {"English": "Dictionaries", "فارسی": "دیکشنری", "کوردی": "فەرهەنگ"},
                    "Tozihat": {"English": "Dictionaries store key-value pairs like a phonebook.", "فارسی": "دیکشنری داده‌ها را به صورت جفت کلید و مقدار\nذخیره می‌کند و مانند دفترچه تلفن\nعمل می‌کند", "کوردی": "فەرهەنگ دراوەکان وەک جووتەی کلیل و بەها هەڵدەگرێت."},
                    "ZirTozihat": {"English": "Keys must be unique.", "فارسی": "کلیدها در این ساختار نمی‌توانند تکراری باشند", "کوردی": "کلیلەکان نابێت دووبارە ببنەوە."},
                    "Code": {"English": "person = {'name': 'Arash', 'age': 20}\nperson['city'] = 'Tehran'\nprint(person['name'])", "فارسی": "person = {'name': 'Arash', 'age': 20}\nperson['city'] = 'Tehran'\nprint(person['name'])", "کوردی": "person = {'name': 'Arash', 'age': 20}\nperson['city'] = 'Tehran'\nprint(person['name'])"},
                    "challenge": {"question": {"English": "Hint: Use curly braces with keys: d = {'name': 'Ali', 'age': 16} and print it.", "فارسی": "راهنمایی: از آکولاد استفاده کن:\nd = {'name': 'Ali', 'age': 16}\nو بعد دیکشنری رو چاپ کن:\nprint(d)", "کوردی": "ڕێنمایی: کەوانە لولپێچەکان بەکاربهێنە:\nd = {'name': 'Ali', 'age': 16}\nو چاپی بکە:\nprint(d)"}, "type": "contains", "expected": {"English": ["{"], "فارسی": ["{"], "کوردی": ["{"]}, "must_include": ["{", "}", ":"], "points": 15}
                },
                "Lesson4": {
                    "id": "data_4",
                    "Title": {"English": "Tuples", "فارسی": "تاپل", "کوردی": "تاپڵ"},
                    "Tozihat": {"English": "Tuples are immutable lists created with `()`.", "فارسی": "تاپل مانند لیست است اما عناصر آن غیرقابل تغییر\nهستند این ساختار با پرانتز\nایجاد می‌شود", "کوردی": "تاپڵ وەک لیستە بەڵام ناتوانرێت بگۆڕدرێت. بە کەوانە `()` دروست دەکرێت."},
                    "ZirTozihat": {"English": "Accessed by index.", "فارسی": "دسترسی به عناصر از طریق ایندکس امکان‌پذیر است", "کوردی": "لە ڕێگەی ئیندێکسەوە دەتوانیت بیانهێنیت."},
                    "Code": {"English": "days = ('Monday', 'Tuesday', 'Wednesday')\nprint(days[0])", "فارسی": "days = ('Monday', 'Tuesday', 'Wednesday')\nprint(days[0])", "کوردی": "days = ('Monday', 'Tuesday', 'Wednesday')\nprint(days[0])"},
                    "challenge": {"question": {"English": "Hint: Tuples are made with parentheses. Write t = (5, 10) and print it.", "فارسی": "راهنمایی: تاپل‌ها با پرانتز ساخته میشن:\nt = (5, 10)\nو بعد چاپش کن:\nprint(t)", "کوردی": "ڕێنمایی: تاپڵ بە کەوانەی ئاسایی دروست دەکرێت:\nt = (5, 10)\nو چاپی بکە:\nprint(t)"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["(", ")"], "points": 10}
                }
            }
        },
        "Dars6": {
            "name": {"English": "Functions", "فارسی": "توابع", "کوردی": "فانکشەنەکان"},
            "Lessons": {
                "Lesson1": {
                    "id": "func_1",
                    "Title": {"English": "Defining Functions", "فارسی": "تعریف تابع و فراخوانی", "کوردی": "پێناسەکردنی فانکشن"},
                    "Tozihat": {"English": "A function is reusable code. Define it with `def`.", "فارسی": "تابع قطعه کدی است که یک بار تعریف شده\nو بارها اجرا می‌شود برای ساخت تابع\nاز کلمه کلیدی\ndef\nاستفاده می‌کنیم", "کوردی": "فانکشن کۆدێکە دەتوانرێت دووبارە بەکاربهێنرێتەوە. بە `def` دروست دەکرێت."},
                    "ZirTozihat": {"English": "It only runs when called.", "فارسی": "تابع تا زمانی که فراخوانی نشود اجرا نمی‌گردد", "کوردی": "تا بانگ نەکرێت جێبەجێ نابێت."},
                    "Code": {"English": "def greet():\n    print('Hello!')\n\ngreet()", "فارسی": "def greet():\n    print('Hello!')\n\ngreet()", "کوردی": "def greet():\n    print('Hello!')\n\ngreet()"},
                    "challenge": {"question": {"English": "Hint: Start with def my_func(): and print your name inside. Call it by writing my_func() outside.", "فارسی": "راهنمایی: با تابع زیر شروع کن:\ndef my_func():\nزیرش اسمت رو پرینت کن. بیرون از تابع بنویس:\nmy_func()", "کوردی": "ڕێنمایی: بەمە دەستپێبکە:\ndef my_func():\nناوت چاپ بکە. لە دەرەوە بانگی بکە:\nmy_func()"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["def "], "points": 10}
                },
                "Lesson2": {
                    "id": "func_2",
                    "Title": {"English": "Parameters & Arguments", "فارسی": "پارامتر و آرگومان", "کوردی": "پارامیتەر و ئارگومێنت"},
                    "Tozihat": {"English": "Variables a function accepts are parameters. Values passed are arguments.", "فارسی": "متغیرهایی که تابع می‌گیرد پارامتر و\nمقادیری که زمان اجرا می‌فرستیم\nآرگومان نام دارند", "کوردی": "ئەو گۆڕاوانەی فانکشن وەریدەگرێت پێیان دەوترێت پارامیتەر."},
                    "ZirTozihat": {"English": "Order matters.", "فارسی": "ترتیب ارسال آرگومان‌ها مهم است", "کوردی": "ڕیزبەندی ناردنیان گرنگە."},
                    "Code": {"English": "def show_product(name, price):\n    print('Product:', name, 'Price:', price)\n\nshow_product('Laptop', 50000)", "فارسی": "def show_product(name, price):\n    print('Product:', name, 'Price:', price)\n\nshow_product('Laptop', 50000)", "کوردی": "def show_product(name, price):\n    print('Product:', name, 'Price:', price)\n\nshow_product('Laptop', 50000)"},
                    "challenge": {"question": {"English": "Hint: Define it as def f(a, b): and print(a, b) inside. Pass two arguments when calling it.", "فارسی": "راهنمایی: تابعت رو اینطوری تعریف کن:\ndef f(a, b):\nو داخلش بنویس:\nprint(a, b)", "کوردی": "ڕێنمایی: بەم شێوەیە پێناسەی بکە:\ndef f(a, b):\nو لەناو بنووسە:\nprint(a, b)"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["def ", ","], "points": 10}
                },
                "Lesson3": {
                    "id": "func_3",
                    "Title": {"English": "Return Values", "فارسی": "مقدار بازگشتی", "کوردی": "بەهای گەڕاوە"},
                    "Tozihat": {"English": "Use `return` to send data back to the caller.", "فارسی": "با دستور\nreturn\nتابع می‌تواند نتیجه\nمحاسبه را به برنامه برگرداند تا\nدر یک متغیر ذخیره شود", "کوردی": "بە فەرمانی `return` ئەنجامەکە دەگەڕێتەوە بۆ بەرنامەکە."},
                    "ZirTozihat": {"English": "Without it, the function returns None.", "فارسی": "بدون این دستور خروجی تابع خالی خواهد بود", "کوردی": "بەبێ ئەم فەرمانە خەرجی فانکشنەکە بەتاڵ دەبێت."},
                    "Code": {"English": "def add(a, b):\n    return a + b\n\nresult = add(3, 5)\nprint(result)", "فارسی": "def add(a, b):\n    return a + b\n\nresult = add(3, 5)\nprint(result)", "کوردی": "def add(a, b):\n    return a + b\n\nresult = add(3, 5)\nprint(result)"},
                    "challenge": {"question": {"English": "Hint: Use return a * b instead of print inside the function. Save the result in a variable and print it.", "فارسی": "راهنمایی: داخل تابع به جای پرینت بنویس:\nreturn a * b\nبیرون تابع نتیجه رو چاپ کن.", "کوردی": "ڕێنمایی: لەناو فانکشنەکە بنووسە:\nreturn a * b\nلە دەرەوەی ئەنجامەکە چاپ بکە."}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["def ", "return", "*"], "points": 15}
                },
                "Lesson4": {
                    "id": "func_4",
                    "Title": {"English": "Built-in Functions", "فارسی": "توابع داخلی پایتون", "کوردی": "فانکشنە ناوەکییەکانی پایتۆن"},
                    "Tozihat": {"English": "Python has ready functions like `len()`, `max()`, `sum()`.", "فارسی": "پایتون توابع آماده‌ای دارد مانند تابع\nlen\nبرای\nطول رشته و توابع\nmax\nو\nmin\nو\nsum\nبرای لیست‌های عددی", "کوردی": "پایتۆن چەندین فانکشنی ئامادەی هەیە وەک `len` و `max` و `sum`."},
                    "ZirTozihat": {"English": "`sorted()` sorts a list.", "فارسی": "تابع\nsorted\nلیست را مرتب‌شده برمی‌گرداند", "کوردی": "فانکشنی `sorted` لیستەکە ڕیز دەکات."},
                    "Code": {"English": "nums = [2, 4, 6]\nprint('Sum:', sum(nums))\nprint('Max:', max(nums))", "فارسی": "nums = [2, 4, 6]\nprint('Sum:', sum(nums))\nprint('Max:', max(nums))", "کوردی": "nums = [2, 4, 6]\nprint('Sum:', sum(nums))\nprint('Max:', max(nums))"},
                    "challenge": {"question": {"English": "Hint: Make a string word = 'Python' and use print(len(word)) to print its length.", "فارسی": "راهنمایی: کافیه یه کلمه بنویسی:\nword = 'Python'\nو بعد با این تابع طولش رو ببینی:\nprint(len(word))", "کوردی": "ڕێنمایی: دەقێک دروست بکە:\nword = 'Python'\nو بەم فەرمانە درێژییەکەی چاپ بکە:\nprint(len(word))"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["len("], "points": 10}
                }
            }
        },
        "Dars7": {
            "name": {"English": "Modules", "فارسی": "ماژول‌ها", "کوردی": "مۆدیوڵەکان"},
            "Lessons": {
                "Lesson1": {
                    "id": "mod_1",
                    "Title": {"English": "Intro to Modules", "فارسی": "آشنایی با ماژول", "کوردی": "ئاشنابوون بە مۆدیوڵ"},
                    "Tozihat": {"English": "A module is a file with ready code. Use `import`.", "فارسی": "ماژول فایلی شامل توابع آماده است\nکه با دستور\nimport\nوارد برنامه می‌شود\nتا از نوشتن کدهای تکراری جلوگیری کند", "کوردی": "مۆدیوڵ فایلێکە کە کۆدی ئامادەی تێدایە. بە `import` هەیە."},
                    "ZirTozihat": {"English": "Standard modules require no installation.", "فارسی": "ماژول‌های استاندارد نیازی به نصب ندارند", "کوردی": "مۆدیوڵە ستانداردەکان پێویستیان بە دابەزاندن نییە."},
                    "Code": {"English": "import math\nprint(math.sqrt(16))", "فارسی": "import math\nprint(math.sqrt(16))", "کوردی": "import math\nprint(math.sqrt(16))"},
                    "challenge": {"question": {"English": "Hint: Write import math. On the next line write print(math.sqrt(25)) to see the output.", "فارسی": "راهنمایی: اول خط بنویس:\nimport math\nتو خط بعدی برای جذر گرفتن بنویس:\nprint(math.sqrt(25))", "کوردی": "ڕێنمایی: بنووسە:\nimport math\nلە دێڕی داهاتوو بنووسە:\nprint(math.sqrt(25))"}, "type": "contains", "expected": {"English": ["5.0"], "فارسی": ["5.0"], "کوردی": ["5.0"]}, "must_include": ["import", "math", "25"], "points": 10}
                },
                "Lesson2": {
                    "id": "mod_2",
                    "Title": {"English": "Standard Modules", "فارسی": "ماژول‌های استاندارد", "کوردی": "مۆدیوڵە ستانداردەکان"},
                    "Tozihat": {"English": "`random` is for random values, `datetime` for time.", "فارسی": "ماژول\nrandom\nبرای تولید مقادیر تصادفی\nو ماژول\ndatetime\nبرای کار با تاریخ\nو زمان سیستم استفاده می‌شوند", "کوردی": "مۆدیوڵی `random` بۆ هەڕەمەکی و `datetime` بۆ کات بەکاردێت."},
                    "ZirTozihat": {"English": "You can import a specific function.", "فارسی": "می‌توان فقط یک تابع خاص را از ماژول وارد کرد", "کوردی": "دەتوانیت تەنها فانکشنێکی دیاریکراو بهێنیت."},
                    "Code": {"English": "import random\nfrom datetime import datetime\n\nprint(random.choice(['Yes', 'No']))\nprint(datetime.now())", "فارسی": "import random\nfrom datetime import datetime\n\nprint(random.choice(['Yes', 'No']))\nprint(datetime.now())", "کوردی": "import random\nfrom datetime import datetime\n\nprint(random.choice(['Yes', 'No']))\nprint(datetime.now())"},
                    "challenge": {"question": {"English": "Hint: import random first. Then use print(random.choice([1, 2, 3])) to get a random item.", "فارسی": "راهنمایی: اول وارد کن:\nimport random\nبعد از متد انتخابی استفاده کن:\nprint(random.choice([1, 2, 3]))", "کوردی": "ڕێنمایی: سەرەتا بنووسە:\nimport random\nپاشان بەکاربهێنە:\nprint(random.choice([1, 2, 3]))"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["random"], "points": 10}
                },
                "Lesson3": {
                    "id": "mod_3",
                    "Title": {"English": "Local Modules", "فارسی": "ماژول‌های محلی", "کوردی": "مۆدیوڵە ناوخۆییەکان"},
                    "Tozihat": {"English": "You can write functions in one file and import them elsewhere.", "فارسی": "شما می‌توانید توابع خود را در یک فایل بنویسید\nو در فایل دیگری آن را وارد کنید\nاین کار به سازماندهی کمک می‌کند", "کوردی": "دەتوانیت فانکشنەکان لە فایلێکدا بنووسیت و لە شوێنێکی تردا بەکاریبهێنیت."},
                    "ZirTozihat": {"English": "The file name is the module name.", "فارسی": "نام فایل همان نام ماژول شماست", "کوردی": "ناوی فایلەکە دەبێتە ناوی مۆدیوڵەکە."},
                    "Code": {"English": "# import my_module\nprint('Loaded')", "فارسی": "# فرض کنید فایلی به نام my_module.py داریم\n# import my_module\n# print(my_module.greet('Ali'))\nprint('ماژول محلی با موفقیت لود شد')", "کوردی": "# import my_module\nprint('مۆدیوڵەکە سەرکەوتووانە هێنرا')"},
                    "challenge": {"question": {"English": "Hint: Just write a simple print statement like print('ok') to simulate loading a local module.", "فارسی": "راهنمایی: به صورت ساده یک پیام پرینت کنی که شبیه‌سازی کنه یک ماژول لود شده:\nprint('ok')", "کوردی": "ڕێنمایی: تەنها پرینتێکی سادە بنووسە بۆ تاقیکردنەوەی مۆدیوڵەکە:\nprint('ok')"}, "type": "contains", "expected": {"English": ["\n"], "فارسی": ["\n"], "کوردی": ["\n"]}, "must_include": ["print"], "points": 10}
                }
            }
        }
    }
}

def isDB():
    for i in tables["isFileHere"]:
        if os.path.exists(f"{i}:/MarcodeProject"):
            return f"{i}:/MarcodeProject/"
    return createDB()

def createDB():
    for i in tables["isFileHere"]:
        try:
            os.mkdir(f"{i}:/MarcodeProject")
            return f"{i}:/MarcodeProject/"
        except:
            pass
    return "ErrorFile"

def getMaxScore():
    totalscore = 0
    for i in tables["DarsHa"].values():
        if "Lessons" in i:
            totalscore += len(i["Lessons"])
    return totalscore or 0
